import { useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box } from "@mui/material";
import SignInSide from "components/sample/sample";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [color, setColor] = useState<any>();
  const arrayElements: any = [
    1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7,
  ];
  const duplicate = [...new Set(arrayElements)];
  console.log(duplicate, "withoutDuplicates");
  const colors = ["red", "blue", "green", "yellow", "pink"];
  useEffect(() => {
    let randomColor = colors[Math.floor(Math.random() * colors.length)];
    setColor(randomColor);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <SignInSide />

        {/* <Box
          bgcolor={color}
          sx={{
            width: "200px",
            height: "200px",
          }}
        ></Box> */}
      </Box>
    </>
  );
}
