import { lazy, useEffect, useState } from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box } from "@mui/material";
import SignInSide from "components/sample/sample";
import SignIn from "components/sample/signIn";
import Demo from "components/sample/demo";
import { RecoilRoot } from "recoil";
import { StrictMode } from "react";

export default function Home() {
  const [showChild, setShowChild] = useState(false);
  const [color, setColor] = useState<any>();
  const [editValue, setEditValue] = useState<boolean>(false);
  console.log("object", editValue);
  // const arrayElements: any = [
  //   1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7,
  // ];
  // const duplicate = [...new Set(arrayElements)];
  // console.log(duplicate, "withoutDuplicates");
  // const colors = ["red", "blue", "green", "yellow", "pink"];
  // useEffect(() => {
  //   let randomColor = colors[Math.floor(Math.random() * colors.length)];
  //   setColor(randomColor);
  // }, []);

  useEffect(() => {
    setShowChild(true);
  }, []);

  if (!showChild) {
    return null;
  }
  if (typeof window === "undefined") {
    return <></>;
  } else {
    return (
      <>
        <Head>
          <title>Create Next App </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box>
          <StrictMode>
            <RecoilRoot>
              <center>
                {/* <SignInSide /> */}
                <Demo setEditValue={setEditValue} />
                <SignIn editValue={editValue} setEditValue={setEditValue} />
              </center>
            </RecoilRoot>
          </StrictMode>
        </Box>
      </>
    );
  }
}
